PRODUCT_VERSION_MAJOR = 12
PRODUCT_VERSION_MINOR = 1

FULIA_VERSION := 1.0

# Internal version
LINEAGE_VERSION := FuliaUI-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(FULIA_VERSION)

# Display version
LINEAGE_DISPLAY_VERSION := FuliaUI-$(PRODUCT_VERSION_MAJOR)-$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(FULIA_VERSION)
